ARG NODE_VERSION=20
FROM localhost/l7/node:${NODE_VERSION}-bookworm
USER root

# if done properly, make this multi-stage and/or add @lavamoat/allow-scripts
# https://github.com/puppeteer/puppeteer/blob/main/docker/Dockerfile

######
######
######
######
# Configure default locale (important for chrome-headless-shell).
ENV LANG en_US.UTF-8

# Install latest chrome dev package and fonts to support major charsets (Chinese, Japanese, Arabic, Hebrew, Thai and a few others)
# Note: this installs the necessary libs to make the bundled version of Chrome that Puppeteer
# installs, work.
# user/group mapping needs to be done in runtime too, if overriding user
COPY ./google-linux_signing_key-*.pub /usr/share/keyrings/googlechrome-linux-keyring.gpg
RUN sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/googlechrome-linux-keyring.gpg] https://dl-ssl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-khmeros fonts-kacst fonts-freefont-ttf libxss1 dbus dbus-x11 \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* \
    && usermod -a -G audio,video node


WORKDIR /usr/local/lib

COPY package.json package-lock.json .

ENV DBUS_SESSION_BUS_ADDRESS autolaunch:

RUN npm i


######
######
######
######

USER node
WORKDIR /
RUN node /usr/local/lib/node_modules/.bin/puppeteer install chromium@latest \
 && node /usr/local/lib/node_modules/.bin/puppeteer install firefox@stable
