ARG ALPINE_VERSION=3.20
ARG BASE_IMAGE=alpine:${ALPINE_VERSION}
#ARG BASE_IMAGE=localhost/l7/nvim:latest

#ARG EXTENSION_BUILDER_IMAGE=localhost/l7/node:20-bookworm
#FROM ${EXTENSION_BUILDER_IMAGE} AS extension-builder
#
#USER root
#COPY --chown=1002:1002 contrib/browser-extensions/multi-account-containers /build/multi-account-containers
#RUN mkdir -p /out /build/multi-account-containers  /tmp/1002-home \
#  && chmod 777 /out /build/multi-account-containers  /tmp/1002-home \
#  && chown 1002:1002 /out /build/multi-account-containers /tmp/1002-home
#
#ENV HOME=/tmp/1002-home
#USER 1002:1002
#
## build, pack, and install web extenstions
#RUN set -x &&  cd /build/multi-account-containers \
#  && npm install --frozen-lockfile \
#  && npm run build \
#  && npm pack
#
#################
FROM ${BASE_IMAGE}
USER root
ARG FIREFOX_RELEASE="firefox-esr"
ARG EXTRA_PKGS=''
RUN apk add --no-cache \
    ${FIREFOX_RELEASE} \
    font-source-code-pro-nerd font-terminus-nerd font-noto-symbols font-noto-emoji font-nerd-fonts-symbols nerd-fonts \
    font-awesome font-adobe-source-code-pro font-jetbrains-mono-nerd ttf-dejavu \
    # font-noto-cjk \
    font-terminus font-noto font-noto-thai font-ipa font-sony-misc font-jis-misc font-inconsolata font-dejavu font-noto font-awesome font-noto-extra font-vollkorn font-misc-cyrillic font-mutt-misc font-screen-cyrillic

COPY imags/X11/firefox/configs/*.js /usr/lib/${FIREFOX_RELEASE}/browser/defaults/preferences/
RUN sed -i 's/^user_pref/pref/' /usr/lib/${FIREFOX_RELEASE}/browser/defaults/preferences/*-*.js \
  && cat /usr/lib/${FIREFOX_RELEASE}/browser/defaults/preferences/*-*.js  >> /usr/lib/${FIREFOX_RELEASE}/browser/defaults/preferences/vendor.js \
  && mkdir -p /usr/lib/${FIREFOX_RELEASE}/distribution \
  && [[ -f /usr/bin/firefox ]] || ln -s ${FIREFOX_RELEASE} /usr/bin/firefox \
  && mkdir -p /tmp/.X11-unix && chmod 177 /tmp/.X11-unix

# trust custom CA in firefox
COPY imags/X11/firefox/policies.json /usr/lib/${FIREFOX_RELEASE}/distribution/policies.json

COPY contrib/browser-extensions/*.xpi \
     /usr/local/browser-extensions/

RUN chown -R user /home/user

USER user

ENTRYPOINT ["firefox"]

