# syntax=docker/dockerfile:1
ARG CADDY_IMAGE=localhost/l7/caddy:latest
ARG GO_VERSION=1.22
FROM ${CADDY_IMAGE} AS fwdproxy
FROM docker.io/golang:${GO_VERSION}-bookworm
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    git curl ca-certificates gnupg ssh-client less psmisc jq time \
    fakeroot \
    build-essential ccache cmake cmake-format distcc zlib1g-dev libzlcore-dev libffi-dev libssl-dev libyaml-dev \
  && rm -rf /var/{cache,lib}/apt

ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOPATH=/home/user/go
ENV GOPROXY="https://goproxy.io,https://proxy.golang.org,direct"

ARG UID=1000
ARG GID=1000
ARG SHELL=/bin/bash

COPY --from=fwdproxy \
  --chmod=444 \
  /data/caddy/pki/authorities/local/root.crt \
  # note: the .crt ending is important
  /usr/local/share/ca-certificates/l7-fwd-proxy.crt

# create user entry and GOPATH
RUN bash -c "groupadd -g ${GID} userz || true" \
  && bash -c "useradd -u ${UID} -g ${GID} -d /home/user -m user -s "${SHELL}" && chown -R ${UID}:${GID} /home/user || true" \
  && mkdir -p /home/user/go \
  && chown -R "${UID}:${GID}" /home/user/go \
  && update-ca-certificates

USER ${UID}:${GID}
ENV HOME=/home/user

# go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.54.2 # supports 1.20 + 1.21
