---
# These services are not actually started
# Just for the sake of being able to do self-contained compose builds,
# either by copying assets from them, or using them as base images.
# Some of these may be usable independently
services:
  build-caddy:
    profiles:
      - build
    build:
      context: imags/caddy
      dockerfile: Containerfile
    image: 'localhost/l7/caddy:latest'
  build-base-alpine:
    profiles:
      - build
      - alpine
    depends_on:
      - build-caddy
    build:
      context: .
      dockerfile: imags/alpine/Containerfile
      args:
        ALPINE_VERSION: '3.20'
        EXTRA_PKGS: ''
      tags:
        - 'localhost/l7/alpine:latest'
        - 'localhost/l7/alpine:3.20'
    image: 'localhost/l7/alpine:latest'

  build-hub:
    profiles:
      - build
      - alpine
    build:
      context: imags/hub
      dockerfile: ./Containerfile
      args:
        EXTRA_PKGS: ''
      tags:
        - 'localhost/l7/hub:latest'
    image: 'localhost/l7/hub:latest'

## derived

  nvim-slim:
    profiles:
      - build
      - alpine
    depends_on:
      - build-base-alpine
    build:
      context: .
      dockerfile: imags/nvim/Containerfile
      args:
        EXTRA_PKGS: ''
    image: 'localhost/l7/nvim:slim'

  podman-remote:
    profiles:
      - build
      - podman
      - alpine
    depends_on:
      - build-base-alpine
    build:
      context: imags/podman-remote
      dockerfile: ./Containerfile
      args:
        EXTRA_PKGS: ''
      tags:
        - 'localhost/l7/podman-remote:alpine'
        - 'localhost/l7/podman-remote:latest'
    image: 'localhost/l7/podman-remote:alpine'

## mixins/combos
  build-nvim-on-podman-remote:
    profiles:
      - build
      - nvim
      - alpine
    depends_on:
      - podman-remote
      #- build-nvim
    build:
      context: .
      dockerfile: imags/nvim/Containerfile
      args:
        EXTRA_PKGS: ''
        BASE_IMAGE: 'localhost/l7/podman-remote:latest'
    image: 'localhost/l7/nvim:podman-remote'

  build-dev-shell:
    profiles:
      - build
      - nvim
      - alpine
    depends_on:
      - build-nvim-on-podman-remote
      - build-hub
    build:
      context: .
      dockerfile: imags/nvim/Containerfile
      args:
        EXTRA_PKGS: ''
        BASE_IMAGE: 'localhost/l7/podman-remote:latest'
    image: 'localhost/l7/nvim:podman-remote'


#### X11

  build-base-alpine-x11:
    ####
    profiles:
      - build
      - alpine
    depends_on:
      - build-base-alpine
    build:
      context: .
      dockerfile: imags/X11/alpine/Containerfile
      args:
        BASE_IMAGE: 'localhost/l7/alpine:3.20'
        EXTRA_PKGS: ''
      tags:
        - 'localhost/l7/alpine:x11-latest'
        - 'localhost/l7/alpine:x11-3.20'
    image: 'localhost/l7/alpine:x11'


  firefox:
    profiles:
      - build
      - alpine
    depends_on:
      - build-base-alpine-x11
    build:
      context: .
      dockerfile: imags/X11/firefox/Containerfile
      args:
        EXTRA_PKGS: ''
        BASE_IMAGE: 'localhost/l7/alpine:x11'
        FIREFOX_RELEASE: firefox
    image: 'localhost/l7/firefox:latest'

  build-podman-remote-on-firefox:
    profiles:
      - build
      - podman
      - alpine
    depends_on:
      - firefox
    build:
      context: imags/podman-remote
      dockerfile: ./Containerfile
      args:
        BASE_IMAGE: 'localhost/l7/firefox:latest'
    image: 'localhost/l7/podman-remote:firefox'

  build-nvim-on-podman-remote-on-firefox:
    profiles:
      - build
      - podman
      - alpine
    depends_on:
      - build-podman-remote-on-firefox
    build:
      context: .
      dockerfile: imags/nvim/Containerfile
      args:
        BASE_IMAGE: 'localhost/l7/podman-remote:firefox'
    image: 'localhost/l7/nvim:firefox'

  build-vnc-on-nvim-on-podman-remote-on-firefox:
    profiles:
      - build
      - vnc
      - alpine
    depends_on:
      - build-nvim-on-podman-remote-on-firefox
    build:
      context: .
      dockerfile: imags/X11/vnc/Containerfile
      args:
        EXTRA_PKGS: 'ratpoison ratpoison-doc'
        BASE_IMAGE: 'localhost/l7/nvim:firefox'
        VNC_DESKTOP: 'ratpoison'
    image: 'localhost/l7/vnc:firefox'

  build-desktop:
    profiles:
      - build
      - vnc
      - nvim
      - alpine
    depends_on:
      #- build-dev-shell
      - build-vnc-on-nvim-on-podman-remote-on-firefox
      - build-hub
    build:
      context: .
      dockerfile: imags/nvim/Containerfile
      args:
        EXTRA_PKGS: ''
        #BASE_IMAGE: 'localhost/l7/podman-remote:latest'
        BASE_IMAGE: 'localhost/l7/vnc:firefox'
    image: 'localhost/l7/nvim:podman-remote-vnc'
