# syntax=docker/dockerfile:1
ARG CADDY_IMAGE=localhost/l7/caddy:latest
ARG NODE_VERSION=20
FROM ${CADDY_IMAGE} AS fwdproxy
FROM docker.io/node:${NODE_VERSION}-bookworm-slim

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    git curl ca-certificates gnupg ssh-client less psmisc jq time man manpages zsh \
    locales fakeroot libpcre3 \
    build-essential ccache cmake cmake-format distcc zlib1g-dev libzlcore-dev libffi-dev libssl-dev libyaml-dev \
  && sed -i '/en_US.UTF-8/s/^# //' /etc/locale.gen \
  && locale-gen \
  && echo 'export PATH="${HOME}/.npm-global/bin:${PATH}"' > /etc/profile.d/global-npm-bins-path \
  && rm -rf /var/{cache,lib}/apt


ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0
ARG NODE_OPTIONS="--no-network-family-autoselection --trace-warnings"

ARG UID=1000
ARG GID=1000
ARG SHELL=/usr/bin/zsh
# if UID differs from default: create new user/group; take over /home/node
RUN  bash -c "[ ${GID} != \"1000\" ] && groupadd -g ${GID} -U node userz || true" \
  && bash -c "[ ${UID} != \"1000\" ] && useradd -u ${UID} -g ${GID} -s ${SHELL} -d /home/node user && chown -R ${UID}:${GID} /home/node || true"

WORKDIR /tmp/
COPY sidecars/node-runner/package.json \
     sidecars/node-runner/package-lock.json \
     .
# remove bundled yarn1 to get corepack integration
RUN rm -rf /usr/local/bin/yarn* /opt/yarn* \
  && npm ci --omit=dev --ignore-scripts \
  && mv node_modules/* node_modules/.bin /usr/local/lib/node_modules/ \
  # seems strange that this is needed
  && ln -s /usr/local/lib/node_modules/ /usr/local/bin/node_modules

COPY --from=fwdproxy \
  --chmod=444 \
  /data/caddy/pki/authorities/local/root.crt \
  # note: the .crt ending is important
  /usr/local/share/ca-certificates/l7-fwd-proxy.crt
ENV NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/l7-fwd-proxy.crt

RUN DEBIAN_FRONTEND=noninteractive dpkg-reconfigure ca-certificates

# default trust github.com known ssh key
COPY contrib/data/ssh_known_hosts /etc/ssh/ssh_known_hosts

####

USER ${UID}:${GID}
ENV HOME=/home/node
# fix broken ipv6 on nodejs v20
ARG NODE_OPTIONS="--no-network-family-autoselection --trace-warnings"
ENV NODE_OPTIONS="${NODE_OPTIONS}"
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global

WORKDIR /tmp

COPY sidecars/node-runner/install-package-managers.sh .
# TODO: integrity checksums / sigchecks for bundled PMs
ARG COREPACK_PMS='yarn@1.22.22 yarn@3 yarn@4 npm@7 npm@9 npm@10 pnpm@9.4'
RUN ./install-package-managers.sh \
  && mkdir -p /home/node/.corepack/bin \
  # `corepack enable` determines shim installation path based on `which corepack` directory
  && ln -s /usr/local/bin/corepack /home/node/.corepack/bin/ \
  && PATH=/home/node/.corepack/bin/:${PATH} corepack enable \
  # ensure ownership
  && mkdir -p /home/node/.cache /home/node/.yarn/berry /home/node/.npm

ENV SHELL=${SHELL}

COPY contrib/l*-scripts/bin/*    /usr/local/bin/
COPY --chown=${UID}:${GID} skel/ /home/node/

ENV PATH=/home/node/.corepack/bin:/usr/local/lib/node_modules/.bin:${PATH}

WORKDIR /src
ENTRYPOINT ["/bin/bash"]
