# syntax=docker/dockerfile:1.4-labs
ARG NODE_VERSION=20
FROM localhost/l7/node:${NODE_VERSION}-bookworm
USER root

# if done properly, make this multi-stage and/or add @lavamoat/allow-scripts
# https://github.com/puppeteer/puppeteer/blob/main/docker/Dockerfile

######
######
######
######
# Configure default locale (important for chrome-headless-shell).
ENV LANG en_US.UTF-8

# https://pptr.dev/troubleshooting/#chrome-doesnt-launch-on-linux
# Install latest chrome dev package and fonts to support major charsets (Chinese, Japanese, Arabic, Hebrew, Thai and a few others)
# Note: this installs the necessary libs to make the bundled version of Chrome that Puppeteer
# installs, work.
# user/group mapping needs to be done in runtime too, if overriding user

ENV PUPPETEER_CACHE_DIR=/opt/puppeteer
COPY ./google-linux_signing_key-*.pub /usr/share/keyrings/googlechrome-linux-keyring.gpg
#RUN sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/googlechrome-linux-keyring.gpg] https://dl-ssl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
#    && apt-get update \
#    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
#      google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-khmeros fonts-kacst fonts-freefont-ttf dbus dbus-x11 \
#      ca-certificates fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils \
#      strace \
#    && rm -rf /var/lib/apt/lists/* \
#    && usermod -a -G audio,video node \
#    && mkdir -p ${PUPPETEER_CACHE_DIR}

RUN sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/googlechrome-linux-keyring.gpg] https://dl-ssl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-khmeros fonts-kacst fonts-freefont-ttf dbus dbus-x11 \
      librsvg2-common \
      fonts-ipafont-* fonts-kacst-one \
      ca-certificates fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils \
      strace \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/* \
    && usermod -a -G audio,video node \
    && mkdir -p ${PUPPETEER_CACHE_DIR}


WORKDIR /usr/local/lib

COPY .npmrc package.json package-lock.json .
# ENV DBUS_SESSION_BUS_ADDRESS autolaunch:

RUN npm i

WORKDIR ${PUPPETEER_CACHE_DIR}
USER root
RUN DEBUG='*' puppeteer browsers install chromium@latest \
 && DEBUG='*' puppeteer browsers install chrome-headless-shell@126.0.6478.126 \
 && DEBUG='*' puppeteer browsers install chrome-headless-shell@127.0.6533.88 \
 && DEBUG='*' puppeteer browsers install chrome-headless-shell@stable \
 && DEBUG='*' puppeteer browsers install firefox@stable \
 && DEBUG='*' puppeteer browsers install chrome@126.0.6478.126 \
 && DEBUG='*' puppeteer browsers install chrome@127.0.6533.88 \
 && DEBUG='*' puppeteer browsers install chrome@stable

RUN ln -sf /opt/puppeteer /home/node/.cache/puppeteer \
  && chown -R node /home/user /home/node

######
######
######
######

USER node
WORKDIR /
