source 'https://rubygems.org'

# Recommended to use http://rbenv.org/ to install and use this version
ruby '>= 3.1.5'

gem 'activesupport', '~> 7.0.8'
gem 'addressable', '~> 2.8'
gem 'bigdecimal'
gem 'bundler', '~> 2.5'
gem 'cocoapods', '~> 1.12'
gem 'concurrent-ruby', '~> 1.3'
gem 'ffi', '~> 1.17'
gem 'i18n', '~> 1.14'
gem 'minitest', '~> 5.24'
