FROM docker.io/alpine:3.19

RUN apk upgrade --no-cache \
  && apk add --no-cache \
    gnupg gnupg-doc gnupg-gpgconf gnupg-lang gnupg-scdaemon gnupg-utils \
    gpg-agent \
    gpg-tui gpg-tui-doc gpg-tui-bash-completion \
    pinentry pinentry-doc pinentry-tty \
    strace \
  && ln -sf pinentry-tty /usr/bin/pinentry
#    pinentry-curses-ss
# for graphical pinentry, one of:
#    pinentry-gnome | pinentry-gtk | pinentry-qt | pinentry-ui

# https://imil.net/blog/posts/2020/testing-gpg-keys-with-docker/
COPY imags/gpg-vault-pk/gpg*.conf /root/.gnupg/
COPY imags/gpg-vault-pk/*.sh /usr/local/bin/

ENV GPG_TTY=/dev/gpgtty
