# syntax=docker/dockerfile:1.4-labs
ARG ALPINE_VERSION=3.20
FROM docker.io/alpine:$ALPINE_VERSION
RUN apk --no-cache add dnsmasq-dnssec dumb-init
EXPOSE 53 53/udp 67/udp 69/udp
ENTRYPOINT ["/usr/bin/dumb-init", "--", "/usr/sbin/dnsmasq", "-k"]
