name: 'oci-image'
on:
  push:
    branches: main
  pull_request:

jobs:
  docker-buildx:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 80:5000
    strategy:
      fail-fast: false
      matrix:
        # test with nonstandard uid and gid
        build-args:
          - |
            UID=1234
            GID=1235
          - |
            UID=1000
            GID=1000
          - ''
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build and load caddy image
        uses: docker/build-push-action@v6
        with:
          context: sidecars/caddy
          file: sidecars/caddy/Containerfile
          load: true
          tags: localhost/l7/caddy:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and load nvim image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Containerfile
          build-args: ${{ matrix.build-args }}
          load: true
          tags: l7/nvim:latest
          # could enable push to gh registry
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and load node-runner image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: sidecars/node-runner/Containerfile
          build-args: ${{ matrix.build-args }}
          load: true
          tags: l7/node:20-bookworm
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and load gpg-vault-pk image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: sidecars/gpg-vault-pk/Containerfile
          build-args: ${{ matrix.build-args }}
          load: true
          tags: l7/gpg-vault:pk
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

  test-make:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        cmd:
          - ''
          - docker
          - podman
        os:
          # todo: make ci work with docker-compose
          # - ubuntu-22.04
          - ubuntu-24.04
        image:
          - gpg_pk
          - nvim
          - runner_node
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: |
          echo '{"insecure-registries" : [ "localhost" ]}' | sudo tee /etc/docker/daemon.json
          sudo apt-get install -y podman-compose --no-install-recommends # podman-remote
          systemctl --user restart podman
          podman compose build http-proxy
          podman save localhost/l7/caddy:latest | docker load
        name: docker build caddy image
        if: ${{ matrix.cmd == 'docker' }}
        env:
          DOCKER_OPTS: "--insecure-registry=localhost"
      - run: |
          sudo apt-get install -y podman-compose --no-install-recommends # podman-remote
          systemctl --user restart podman
          podman compose build http-proxy
        name: podman build caddy image
        if: ${{ matrix.cmd != 'docker' }}
        env:
          DOCKER_OPTS: "--insecure-registry=localhost"
      - run: |
          make IMAGE_NAME=localhost/foo-${{ matrix.image }} IMAGE_TAG=bar CMD=${{ matrix.cmd }} image_${{ matrix.image }}
        if: ${{ matrix.cmd != '' }}
        name: build ${{ matrix.image }} image
        env:
          CMD: ${{ matrix.cmd }}
          DOCKER_OPTS: "--insecure-registry=localhost"
      - run: |
          make IMAGE_NAME=localhost/foo-${{ matrix.image }} IMAGE_TAG=bar image_${{ matrix.image }}
        if: ${{ matrix.cmd == '' }}
        name: build ${{ matrix.image }} image
        env:
          DOCKER_OPTS: "--insecure-registry=localhost"
      - run: |
          ${{ matrix.cmd }} image inspect localhost/foo-${{ matrix.image }}:bar
        if: ${{ matrix.cmd != '' }}
        name: inspect ${{ matrix.image }} image
        env:
          CMD: ${{ matrix.cmd }}
          DOCKER_OPTS: "--insecure-registry=localhost"
      - run: |
          export CONTAINER_HOST="unix://${XDG_RUNTIME_DIR}/podman/podman.sock"
          podman image inspect localhost/foo-${{ matrix.image }}:bar
        if: ${{ matrix.cmd == '' }}
        name: inspect ${{ matrix.image }} image
        env:
          DOCKER_OPTS: "--insecure-registry=localhost"
      - run: |
          export CONTAINER_HOST="unix://${XDG_RUNTIME_DIR}/podman/podman.sock"
          make test
        name: make test
        env:
          DOCKER_OPTS: "--insecure-registry=localhost"
