# syntax=docker/dockerfile:1.4-labs
#ARG BASE_IMAGE=localhost/l7/alpine:3.20
ARG BASE_IMAGE=localhost/l7/podman-remote:alpine

FROM ${BASE_IMAGE}

# EXTRA_PKGS get installed in final image. examples of useful extra packages:
### secrets injection
## ARG EXTRA_PKGS='age pass gopass'
### TUI file managers
## ARG EXTRA_PKGS='ncdu ranger vifm'
### open links in host browser
## ARG EXTRA_PKGS='xdg-open'
### yes, you can integrate with system clipboard
## ARG EXTRA_PKGS='xsel xclip wl-clipboard'
## ARG EXTRA_PKGS='terminus-fonts fontawesome-fonts-all gdouros-symbola-fonts'
### monitoring etc, probably more useful on host
## ARG EXTRA_PKGS='htop sysstat ncdu net-tools'
##
# nice-to-haves
# EXTRA_PKGS='bat libnotify w3m'
# gpg hardware tokens ssh
## ARG EXTRA_PKGS='openssh-sk-helper'

ARG EXTRA_PKGS='bat'

ARG HOME=/home/user
ENV HOME=${HOME}
ARG SHELL=/bin/bash
ARG UID=1000
ARG GID=1000

USER root
RUN apk add --no-cache \
    neovim neovim-doc \
    tree-sitter tree-sitter-bash tree-sitter-cli tree-sitter-cmake tree-sitter-comment tree-sitter-css tree-sitter-embedded-template tree-sitter-html tree-sitter-ini tree-sitter-javascript tree-sitter-jsdoc tree-sitter-json tree-sitter-lua tree-sitter-python tree-sitter-regex tree-sitter-ruby tree-sitter-toml tree-sitter-typescript \
    # tree-sitter-grammars \  # everything
    # tree-sitter-go tree-sitter-go-mod tree-sitter-java tree-sitter-rust \
    diffutils tree fzf ripgrep \
    github-cli tig \
    markdown \
    coreutils less grep sed findutils file \
    screen tmux \
    which \
    ${EXTRA_PKGS} \
  && apk add  --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/edge/testing tree-sitter-markdown \
  && ln -sf nvim /usr/bin/vim

COPY --chown=2:2 \
  contrib/nvim-plugins /etc/xdg/nvim/pack/build-l7ide/start

RUN cat /etc/xdg/nvim/pack/build-l7ide/start/tokyonight.nvim/extras/fzf/tokyonight_moon.sh >> /home/user/.env

ARG TMUX_THEME_PATH="/home/user/.config/tmux/tokyonight/tokyonight_night.tmux"
ENV TMUX_THEME_PATH="${TMUX_THEME_PATH}"

USER ${UID}:${GID}
WORKDIR /src
ENTRYPOINT /usr/bin/nvim
